### PR TITLE
Make sure there aren't two swapiness settings

### PR DESCRIPTION
**Pull request by jonathangreen**
In #4 we added a swappiness setting. If it happens to be already defined the config file will end up with two instances of the setting. This attempts to prevent that.

For instance:
```
TASK [server : set server swappiness] ******************************************
changed: [dev-islandora]
--- before: /etc/sysctl.conf (content)
+++ after: /etc/sysctl.conf (content)
@@ -61,3 +61,4 @@
 net.ipv4.tcp_syncookies=1
 net.ipv4.tcp_synack_retries=2
 vm.swappiness=25
+vm.swappiness = 10
```

### CODE REVIEW

**Comment by jonathangreen** [comment]
@Blake- @mark-cooper what do you guys think?

**Comment by Blake-** [comment]
Odd, I would've thought  "regexp: "^vm.swappiness" would avoid the newline if it's already there.

**Comment by jonathangreen** [comment]
@Blake- thats a way better fix. I changed to the pull request to just add a regex.

**Comment by mark-cooper** [comment]
👍

**Pull request merged**
