### PR TITLE
Update lineinfile for login-notify.sh

### PR DESCRIPTION
**Pull request by jonathangreen**
When running this on is-dev with --check --diff I am seeing this:

```
TASK [server : require ssh login-notify.sh script in pam.d/sshd] ***************
changed: [dev-islandora]
--- before: /etc/pam.d/sshd (content)
+++ after: /etc/pam.d/sshd (content)
@@ -36,4 +36,4 @@
 session    required     pam_env.so user_readenv=1 envfile=/etc/default/locale
 
 # Standard Un*x password updating.
-@include common-password
+session optional pam_exec.so seteuid /etc/ssh/login-notify.sh
```

I'm fairly sure we don't want to be replacing `@include common-password`.

### CODE REVIEW

**Comment by mark-cooper** [comment]
@Blake- do you know the effect of this change?

```
 # Standard Un*x password updating.
-@include common-password
+session optional pam_exec.so seteuid /etc/ssh/login-notify.sh
```

Do we need to restore `@include common-password` wherever it's missing?

**Comment by Blake-** [comment]
`ops@omd:~/projects/sysadmin-playbooks$ ansible -i ./softlayer.py all  --limit=islandora -e ansible_ssh_port=922 -K -u lyrasis -s -m shell -a  'grep common-password /etc/pam.d/sshd'`

`SUCCESS | rc=0 >> @include common-password` on all so we're ok on that.

**Comment by jonathangreen** [comment]
```
# /etc/pam.d/common-password - password-related modules common to all services
#
# This file is included from other service-specific PAM config files,
# and should contain a list of modules that define the services to be
# used to change user passwords.  The default is pam_unix.

# Explanation of pam_unix options:
#
# The "sha512" option enables salted SHA512 passwords.  Without this option,
# the default is Unix crypt.  Prior releases used the option "md5".
#
# The "obscure" option replaces the old `OBSCURE_CHECKS_ENAB' option in
# login.defs.
#
# See the pam_unix manpage for other options.

# As of pam 1.0.1-6, this file is managed by pam-auth-update by default.
# To take advantage of this, it is recommended that you configure any
# local modules either before or after the default block, and use
# pam-auth-update to manage selection of other modules.  See
# pam-auth-update(8) for details.

# here are the per-package modules (the "Primary" block)
password        [success=1 default=ignore]      pam_unix.so obscure sha512
# here's the fallback if no module succeeds
password        requisite                       pam_deny.so
# prime the stack with a positive return value if there isn't one already;
# this avoids us returning an error just because nothing sets a success code
# since the modules above will each just jump around
password        required                        pam_permit.so
# and here are more per-package modules (the "Additional" block)
# end of pam-auth-update config
```

Looks like the file is used mostly for password changes. Seems like the biggest consequence of not having it would be that if a user changes their password the hash may fall back to unix crypt, which is kind of a crappy hashing algorithm these days. Not catastrophic to security at all but it might be a good line to add back in.

**Comment by Blake-** [comment]
Added a to-do in the list.

**Pull request merged**
