### PR TITLE
Add email subject to alert and change noalert to alert

### PR DESCRIPTION
**Pull request by Blake-**
Not sure why this was noalert?
This adds configurable email subjects for different alerts. I'd like the disk space one especially to SCREAM AT ME.

### CODE REVIEW

**Comment by mark-cooper** [comment]
It's supposed to be no alert if `server_monit_alerts_services_only` is true. It looks slightly weird (did I do that? =/), but it's correct. If `server_monit_alerts_services_only` is false then no alert will not be set, and alerts should be getting through (unless something is wrong elsewhere). Are alerts not working?

**Comment by Blake-** [comment]
ahhhh, yes, makes sense now! Totally misread.

**Comment by Blake-** [comment]
@mark-cooper Does this look correct now?

**Comment by mark-cooper** [comment]
It looks like the subjects (such as `server_monit_alert_system_load_email_subject`) are intended to be variables, but they are are undefined for the role. Each subject line variable should get a default value. They'll also need to be wrapped in the template (i.e. `{{ server_monit_alert_system_load_email_subject }}`)

**Comment by mark-cooper** [comment]
@Blake- close?

**Pull request closed without merging**
